Repository TeamChaRo/ChaRo-Server, pull requests merged in 2021-07, with the labels that each got.

#6 Feat/1
  package-lock.json
  package.json
  src/Loaders/connect.ts
  src/Loaders/db.ts
  src/config/config.ts
  src/index.ts
  src/models/User.ts
  src/models/a.txt
  src/models/index.js
  src/models/index.ts
  src/models/theme.ts
  src/models/warning.ts
Labels: DB관련

#10 [Feat/8] 앱잼용 DB 모델 확정! 진짜 끝 !!
  src/interface/res/briefInformationDTO.ts
  src/interface/res/detailDTO.ts
  src/interface/res/mainDTO.ts
  src/interface/res/searchHistory.ts
  src/interface/res/showMoreDTO.ts
  src/models/Banner.ts
  src/models/Course.ts
  src/models/Custom.ts
  src/models/Local.ts
  src/models/Post.ts
  src/models/PostHasImage.ts
  src/models/SearchHistory.ts
  src/models/User.ts
  src/models/index.ts
  src/models/theme.ts
  src/models/warning.ts
Labels: DB관련, 완료

#12 [feat/11] post_has_theme 테이블 생성
  src/models/index.ts
Labels: DB관련, 완료

#15 [Feat/12] Course 테이블에 출발지, 목적지 위도경도 컬럼 추가 🚙
  src/models/Course.ts
Labels: DB관련

#21 [Feat/3] 이미지 업로드 모듈 작성
  package-lock.json
  package.json
  src/api/a.txt
  src/config/config.ts
  src/controller/image.ts
Labels: API

#23 [Feat/22] mainDTO 내에 차로의 오늘추천드라이브, 요즘뜨는 드라이브 추가
  src/interface/res/briefInformationDTO.ts
  src/interface/res/mainDTO.ts
Labels: enhancement

#34 [Feat/29] 더보기 API 기능 구현
  src/api/preview.ts
  src/config/config.ts
  src/controller/index.ts
  src/controller/previewController.ts
  src/index.ts
  src/interface/res/previewDTO.ts
  src/service/previewLocalService.ts
  src/service/previewMap.json
  src/service/previewThemeService.ts
  src/service/previewTodayService.ts
  src/service/writePostService.ts
Labels: API, 완료

#49 [feat] 마케팅푸시, 마케팅이메일 동의 컬럼 추가(pushAlarm은 컬럼명 변경)
  src/models/User.ts
Labels: DB관련

#51 [Feat/48] 더보기 최신순 필터 API 기능 구현
  src/api/preview.ts
  src/controller/index.ts
  src/controller/previewController.ts
  src/service/briefCollectionService.ts
  src/service/likePreviewService.ts
  src/service/newPreviewService.ts
  src/service/previewLocalService.ts
  src/service/previewThemeService.ts
  src/service/previewTodayService.ts
Labels: API, 더보기 뷰, 완료

#53 [Feat/46] 로그인/회원가입 프로세스 완성 ✅
  src/api/sign.ts
  src/controller/signController.ts
  src/index.ts
  src/interface/req/userDTO.ts
  src/service/idCheckService.ts
  src/service/nicknameCheckService.ts
  src/service/signInService.ts
  src/service/signUpService.ts
Labels: API, 지은🐰

#55 [feat] 상세조회 API isAuthor 변수 추가
  src/interface/res/detailDTO.ts
  src/service/postDetailService.ts
Labels: API, 게시글 관련, 지은🐰

#66 [Feat/57] 인기순 검색하기 API 구현 ✅
  src/api/search.ts
  src/controller/searchController.ts
  src/index.ts
  src/interface/req/searchDTO.ts
  src/service/likeSearchService.ts
Labels: API, 검색뷰, 지은🐰

#73 [Feat/71] 게시글 상세조회, 검색(인기순, 최신순) 성능 개선 ⚙️
  src/service/likeSearchService.ts
  src/service/newSearchService.ts
  src/service/postDetailService.ts
Labels: 검색뷰, 성능 향상, 지은🐰

#78 [fix] postDetailService - likesCount 추가
  src/service/postDetailService.ts
Labels: API, bug, 게시글 관련, 지은🐰

#80 [style] postDetailController - console.log 삭제
  src/service/postDetailService.ts
Labels: 게시글 관련, 지은🐰

#89 [Docs/1] README.md 최신화 업데이트 (21.07.16)
  README.md
Labels: 문서, 지은🐰

#95 [feat] sign/signIn res body에 profileImage 추가
  src/service/signInService.ts
Labels: API, 인증관련, 지은🐰

#96 [Feat/91] 검색뷰 주의사항 제외하고 검색되도록 쿼리문 수정
  src/service/likeSearchService.ts
  src/service/newSearchService.ts
Labels: API, 검색뷰, 예원🐣, 지은🐰

#97 [fix] postDetail isParking 버그 수정
  src/service/postDetailService.ts
Labels: API, bug, 지은🐰
